type: Model
name: product_classification_example
index: id
target: label
columns:
  - type: TEXT
    name: text
  - type: CATEGORICAL
    name: label
train:
  metric: f1_macro
  exclude_ensemble: True
  disable_automl_feature_generation: True
  disable_feature_importance: True
  disable_data_profiling: True
  disable_feature_timestamp_generation: True
  size: large
  included_model_types:
    - distilbert
    - RandomForest
    - Linear
    - GBM
predict:
  schedule: 0 4 * * 0
  incremental: True
promote:
  policy: best
table: tmls.cfpb.sample_consumer_complaints
